//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> StartID { get; set; }
        public Nullable<int> EndID { get; set; }
        public int ID { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
