//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chain
    {
        public int ID { get; set; }
        public string NWA { get; set; }
        public string NWOA { get; set; }
        public string NID { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<int> ChainNo { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
