//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bukhari_DataSQLEntities : DbContext
    {
        public Bukhari_DataSQLEntities()
            : base("name=Bukhari_DataSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Chain> Chains { get; set; }
        public virtual DbSet<FullHadith> FullHadiths { get; set; }
        public virtual DbSet<UniqueChain> UniqueChains { get; set; }
        public virtual DbSet<UniqueNarrator> UniqueNarrators { get; set; }
        public virtual DbSet<Narrator> Narrators { get; set; }
    }
}
