//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narrator
    {
        public int Id { get; set; }
        public Nullable<int> NarratorID { get; set; }
        public string NarratorNameWithArab { get; set; }
        public string NarratorNameWithoutArab { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<int> ChainNo { get; set; }
    }
}
