//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqueNarrator
    {
        public int ID { get; set; }
        public Nullable<int> NarratorID { get; set; }
        public string NarratorWithArab { get; set; }
        public string NarratorWithoutArab { get; set; }
        public string RName { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
